apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: topic1
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 2
  config:
    # retention 7200000 = 2 hours
    retention.ms: 7200000
    segment.bytes: 1073741824

