apiVersion: monitoring.coreos.com/v1
kind: GrafanaDataSource
metadata:
  name: grafana-datasource
  namespace: kafka-monitor
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        timeInterval: 5s
      name: Prometheus
      type: prometheus
      url: 'http://prometheus-operated:9090'
      version: 1
  name: grafana-datasources.yaml
